#!/bin/sh -e
mkdir -p "$1/etc/pacman.d"
curl -Lo \
	"$1/etc/pacman.d/mirrorlist-arch" \
	"https://www.archlinux.org/mirrorlist/all/"
echo "Remember to enable mirrors in /etc/pacman.d/mirrorlist-arch!"
