#!/bin/sh -e

export DESTDIR="$1"
export CFLAGS="$CFLAGS"
export CXXFLAGS="$CXXFLAGS"

mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make
make DESTDIR="$1" install

mkdir -p "$1/usr/lib/ccache/bin"
host=$(cc -dumpmachine)

for link in \
    cc  "$host-cc"  \
    gcc "$host-gcc" \
    g++ "$host-g++" \
    cpp "$host-cpp" \
    c++ "$host-c++"
do
    ln -sf /usr/bin/ccache "$1/usr/lib/ccache/bin/$link"
done
